/**
 * Route Tree (Generated)
 *
 * This file would normally be auto-generated by TanStack Router's
 * route generator plugin. For the example, we define it manually.
 *
 * In a real project, run `tsr generate` or let the Vite plugin
 * handle this automatically.
 */

import { rootRoute } from "./routes/__root";
import { indexRoute } from "./routes/index";
import { aboutRoute } from "./routes/about";
import { postsRoute } from "./routes/posts";
import { postRoute } from "./routes/posts.$postId";

// Build the route tree
const routeTree = rootRoute.addChildren([
  indexRoute,
  aboutRoute,
  postsRoute.addChildren([postRoute]),
]);

export { routeTree };
